order_converter/conversion/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/order/create')),
    url(r'^create/$', views.create, name='order'),
    url(r'^history/$', views.history, name='history'),

	url(r'^send/$', views.sendOrder, name='send'),

    url(r'^show/(?P<id>\w{0,50})/$', views.show, name='show'),
]

order_converter/order_converter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^$', RedirectView.as_view(url='/order')),
    url(r'^admin/', admin.site.urls),
    url(r'^order/', include('conversion.urls')),
]

order_converter/conversion/models.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from datetime import datetime

# Create your models here.
from xml.etree import cElementTree as ElementTree
import lxml.etree as etree
from pprint import pprint
import json
import sys
from xml.sax.saxutils import escape

from xml.dom.minidom import Text, Element

#from modules.order_conv import conv
from order_conv import conv, OrderDict


class Order(models.Model):
	name   = models.CharField(max_length=255)
	file   = models.FileField(upload_to="orders/")
	date   = models.DateTimeField(default=datetime.now, blank=True)
	count_order  = models.IntegerField(default=0)

	soaps = []

	def conv(self):
		print("Conversion : "+str(self.file))
		arr = conv(['truc', self.file, 'LOE_EUR', 'xml'])
		self.soaps = arr[1]
		self.orders = arr[0]
		self.count_order = len(self.orders)
		self.save()
		print self.orders
		return 0

	    
	def __str__(self):
		return self.name

order_converter/conversion/forms.py
#-*- coding: utf-8 -*-

from django import forms


class ContactForm(forms.Form):
    sujet = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    envoyeur = forms.EmailField(label="Votre adresse mail")
    renvoi = forms.BooleanField(help_text="Cochez si vous souhaitez obtenir une copie du mail envoyé.", required=False)


class NewContactForm(forms.Form):
    nom = forms.CharField()
    adresse = forms.CharField(widget=forms.Textarea)
    photo = forms.ImageField()


class OrderForm(forms.Form):
	name = forms.CharField()
	file = forms.FileField()

order_converter/conversion/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from datetime import datetime

import requests
import json

from .forms import ContactForm
from .forms import NewContactForm
from .forms import OrderForm

from conversion.models import Order
import base64

# /order/create
def create(request):
    sauvegarde = False
    form = OrderForm(request.POST or None, request.FILES)
    print form

    if "file" in form.cleaned_data.keys():
        order = Order()
        order.name = 'test'+str(datetime.now())
        order.file = form.cleaned_data["file"]
        order.save()
        sauvegarde = True
        id = order.id

        return HttpResponseRedirect('/order/show/'+str(id), {'data': 'toto' })
 
    return render(request, 'order_cegid/create.html', {
        'form': form, 
        'sauvegarde': sauvegarde
    })



# /order/show
def show(request, id):
    order = Order.objects.get(id=id)
    order.conv()
    return render(request, 'order_cegid/show.html', {'date': datetime.now(), 'length': len(order.orders), 'data': order, 'message': request.GET})

# /history
def history(request):
    return render(request, 'order_cegid/history.html', {'date': datetime.now(), 'id' : id, 'data': Order.objects.all()})


# POST : /send
def sendOrder(request):
    print request
    #form = OrderForm(request.POST or None, request.FILES)
    data = (request.POST['soap']).encode('utf-8')
    username = request.POST['username']
    password = request.POST['password']
    print username
    print password

    print data
    headers = {
    'Content-Type': 'text/xml;charset=UTF-8',
    'SOAPAction': "http://www.cegid.fr/Retail/1.0/ISaleDocumentService/Create",
    'Authorization': 'Basic '+base64.b64encode(username+':'+password.encode('ascii'))
    }

    url = 'http://nty2web.es.loewe/Y2_DEV/SaleDocumentService.svc'
    response = requests.post(url,  data=data, headers=headers)
    print response.status_code
    print response.text

    return HttpResponse(response.text, content_type='text/xml')

order_converter/conversion/templates/order_cegid/base.html
<!DOCTYPE html>
<html lang="fr">

<head>   
    <title>{% block title %}show{% endblock %}</title>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="/static/css/codemirror.css">
    <link rel="stylesheet" href="/static/css/show-hint.css">
    <link rel="stylesheet" href="/static/css/monokai.css">
    <link rel="stylesheet" href="/static/css/dialog.css">

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/prism.css">

    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/js/prism.js"></script>


    <script type="text/javascript" src="/static/js/codemirror.js"></script>


<script type="text/javascript" src="/static/js/search.js"></script>
<script type="text/javascript" src="/static/js/searchcursor.js"></script>
<script type="text/javascript" src="https://codemirror.net/addon/search/jump-to-line.js"></script>

<script type="text/javascript" src="/static/js/formatting.js"></script>

<script type="text/javascript" src="/static/js/show-hint.js"></script>
<script type="text/javascript" src="/static/js/xml-hint.js"></script>
<script type="text/javascript" src="/static/js/xml.min.js"></script>

<script type="text/javascript" src="/static/js/dialog.js"></script>

<script src="/static/js/vkbeautify.js"></script>

    <!-- {% load static %}  -->
</head>




<body>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Order SFCC To Cegid</a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/order/create">Import a file<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/order/history">History</a>
    </div>
  </div>
</nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

order_converter/conversion/templates/order_cegid/create.html
{% extends "base.html" %}
{% block title %}Create{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <h1>Upload your xml file</h1>

    {% if sauvegarde %}
      <p>Got it !!!</p>
    {% endif %}
   </div>

  <div class="row">
    <p>
      <form method="post" enctype="multipart/form-data" action=".">
        {% csrf_token %}
          <ul class="errorlist"><li>This field is required.</li></ul>
          <p><label for="id_file">File:</label> <input id="id_file" name="file" required="" type="file"></p>
          <button type="submit" class="btn btn-dark">Submit</button>
        </form>
      </p>
    </div>
  </div>

{% endblock %}

order_converter/conversion/templates/order_cegid/date.html
<h1>Bienvenue sur mon blog</h1>

<p>La date actuelle est : {{ date }}</p>

order_converter/conversion/templates/order_cegid/history.html
{% extends "base.html" %}
{% block title %}Show{% endblock %}




{% block content %}
<h1>History</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Filename</th>
      <th>count</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>

{% for item in data%}
    <tr>
      <th scope="row">{{ item.id }}</th>
      <td>{{ item.file }}</td>
      <td>{{ item.count_order }}</td>
      <td>{{ item.date }}</td>
      <td><a href="/order/show/{{ item.id }}">View</a></td>
    </tr>
{% endfor %}

  </tbody>
</table>

{% endblock %}

order_converter/conversion/templates/order_cegid/show.html
{% extends "base.html" %}
{% block title %}Show{% endblock %}




{% block content %}
<h1>Validation</h1>
<p>{{ date }}</p>


<div class="container-fluid">

        <nav class="nav nav-tabs" id="myTab" role="tablist">
        {% for item in data.orders %}
        {% if forloop.counter0 == 0 %}
            <a class="nav-item nav-link active"  data-toggle="tab" href="#{{ forloop.counter0 }}" role="tab" aria-selected="true">{{ item }}</a>
        {% else %}
            <a class="nav-item nav-link"  data-toggle="tab" href="#{{ forloop.counter0 }}" role="tab" aria-selected="false">{{ item }}</a>
        {% endif %}
        {% endfor %}
        </nav>


        <div class="tab-content" id="nav-tabContent">
        {% for item in data.soaps %}
        {% if forloop.counter0 == 0 %}

            <div class="tab-pane fade show active" id="{{ forloop.counter0 }}" role="tabpanel">
                <form method="post" enctype="multipart/form-data" action="/order/send/">
                {% csrf_token %}

                    <hr/>
                    <div class="form-group">
                        <textarea id="code#{{ forloop.counter0 }}" style="resize: vertical" name="soap">{{item}}</textarea>
                    </div>

                    <div class="form-group">
                        <p><label for="username">Username</label> <input id="username" class="form-control" type="text" name="username" maxlength="100" /></p>
                        <p><label for="password">Password</label> <input id="password" type="password" class="form-control" name="password" maxlength="100" /></p>
                    </div>
                    <button type="submit" class="btn btn-dark" >Send to Cegid</button>
                </form>
                <hr/>
            </div>


        {% else %}
            <div class="tab-pane fade" id="{{ forloop.counter0 }}"" role="tabpanel">
                <form method="post" enctype="multipart/form-data" action="/order/send/">
                {% csrf_token %}
                    <hr/>          
                    <div class="form-group">
                        <textarea id="code#{{ forloop.counter0 }}" class="form-control" name="soap">{{item}}</textarea>
                    </div>

                    <div class="form-group">
                        <p><label for="username">Username</label> <input id="username" class="form-control" type="text" name="username" maxlength="100" /></p>
                        <p><label for="password">Password</label> <input id="password" type="password" class="form-control" name="password" maxlength="100" /></p>
                    </div>

                    <button type="submit" class="btn btn-dark" >Send to Cegid</button>
                </form>
            <hr/>
            </div>
            {% endif %}
            {% endfor %}
        </div>
</div>
    


<script type="text/javascript">


document.getElementById("code#0").value = vkbeautify.xml(document.getElementById("code#0").value);

var editor = CodeMirror.fromTextArea(document.getElementById("code#0"), {
    mode: "xml",
    theme: 'monokai',
    lineNumbers: true
});

editor.refresh();


$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    //var target = $(e.target).attr("id") // activated tab
    document.getElementById("code"+e.currentTarget.hash).value = vkbeautify.xml(document.getElementById("code"+e.currentTarget.hash).value);
    editor.toTextArea();
    editor = CodeMirror.fromTextArea(document.getElementById("code"+e.currentTarget.hash), {
        mode: "xml",
        theme: 'monokai',
        lineNumbers: true
    });     
    editor.refresh();
});
</script>


{% endblock %}